/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ForClinicsRouteImport } from './routes/for-clinics'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClinicsRouteImport } from './routes/clinics'
import { Route as ClinicRouteImport } from './routes/clinic'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PatientIndexRouteImport } from './routes/patient.index'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as PatientProfileRouteImport } from './routes/patient.profile'
import { Route as PatientFavoritesRouteImport } from './routes/patient.favorites'
import { Route as PatientAppointmentsRouteImport } from './routes/patient.appointments'
import { Route as ClinicOnboardingRouteImport } from './routes/clinic.onboarding'
import { Route as CSlugRouteImport } from './routes/c.$slug'
import { Route as BookDoctorIdRouteImport } from './routes/book.$doctorId'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClinicsRoute = ForClinicsRouteImport.update({
  id: '/for-clinics',
  path: '/for-clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicsRoute = ClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicRoute = ClinicRouteImport.update({
  id: '/clinic',
  path: '/clinic',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientIndexRoute = PatientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PatientRoute,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClinicRoute,
} as any)
const PatientProfileRoute = PatientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => PatientRoute,
} as any)
const PatientFavoritesRoute = PatientFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => PatientRoute,
} as any)
const PatientAppointmentsRoute = PatientAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => PatientRoute,
} as any)
const ClinicOnboardingRoute = ClinicOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ClinicRoute,
} as any)
const CSlugRoute = CSlugRouteImport.update({
  id: '/c/$slug',
  path: '/c/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/clinic': typeof ClinicRouteWithChildren
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/for-clinics': typeof ForClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/c/$slug': typeof CSlugRoute
  '/clinic/onboarding': typeof ClinicOnboardingRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/clinic/': typeof ClinicIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/for-clinics': typeof ForClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/c/$slug': typeof CSlugRoute
  '/clinic/onboarding': typeof ClinicOnboardingRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/clinic': typeof ClinicIndexRoute
  '/patient': typeof PatientIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/clinic': typeof ClinicRouteWithChildren
  '/clinics': typeof ClinicsRoute
  '/contact': typeof ContactRoute
  '/for-clinics': typeof ForClinicsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/patient': typeof PatientRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/c/$slug': typeof CSlugRoute
  '/clinic/onboarding': typeof ClinicOnboardingRoute
  '/patient/appointments': typeof PatientAppointmentsRoute
  '/patient/favorites': typeof PatientFavoritesRoute
  '/patient/profile': typeof PatientProfileRoute
  '/clinic/': typeof ClinicIndexRoute
  '/patient/': typeof PatientIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/clinic'
    | '/clinics'
    | '/contact'
    | '/for-clinics'
    | '/forgot-password'
    | '/login'
    | '/patient'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/book/$doctorId'
    | '/c/$slug'
    | '/clinic/onboarding'
    | '/patient/appointments'
    | '/patient/favorites'
    | '/patient/profile'
    | '/clinic/'
    | '/patient/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/clinics'
    | '/contact'
    | '/for-clinics'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/book/$doctorId'
    | '/c/$slug'
    | '/clinic/onboarding'
    | '/patient/appointments'
    | '/patient/favorites'
    | '/patient/profile'
    | '/clinic'
    | '/patient'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/clinic'
    | '/clinics'
    | '/contact'
    | '/for-clinics'
    | '/forgot-password'
    | '/login'
    | '/patient'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/terms'
    | '/book/$doctorId'
    | '/c/$slug'
    | '/clinic/onboarding'
    | '/patient/appointments'
    | '/patient/favorites'
    | '/patient/profile'
    | '/clinic/'
    | '/patient/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ClinicRoute: typeof ClinicRouteWithChildren
  ClinicsRoute: typeof ClinicsRoute
  ContactRoute: typeof ContactRoute
  ForClinicsRoute: typeof ForClinicsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PatientRoute: typeof PatientRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  CSlugRoute: typeof CSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clinics': {
      id: '/for-clinics'
      path: '/for-clinics'
      fullPath: '/for-clinics'
      preLoaderRoute: typeof ForClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinics': {
      id: '/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof ClinicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic': {
      id: '/clinic'
      path: '/clinic'
      fullPath: '/clinic'
      preLoaderRoute: typeof ClinicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/': {
      id: '/patient/'
      path: '/'
      fullPath: '/patient/'
      preLoaderRoute: typeof PatientIndexRouteImport
      parentRoute: typeof PatientRoute
    }
    '/clinic/': {
      id: '/clinic/'
      path: '/'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/patient/profile': {
      id: '/patient/profile'
      path: '/profile'
      fullPath: '/patient/profile'
      preLoaderRoute: typeof PatientProfileRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/favorites': {
      id: '/patient/favorites'
      path: '/favorites'
      fullPath: '/patient/favorites'
      preLoaderRoute: typeof PatientFavoritesRouteImport
      parentRoute: typeof PatientRoute
    }
    '/patient/appointments': {
      id: '/patient/appointments'
      path: '/appointments'
      fullPath: '/patient/appointments'
      preLoaderRoute: typeof PatientAppointmentsRouteImport
      parentRoute: typeof PatientRoute
    }
    '/clinic/onboarding': {
      id: '/clinic/onboarding'
      path: '/onboarding'
      fullPath: '/clinic/onboarding'
      preLoaderRoute: typeof ClinicOnboardingRouteImport
      parentRoute: typeof ClinicRoute
    }
    '/c/$slug': {
      id: '/c/$slug'
      path: '/c/$slug'
      fullPath: '/c/$slug'
      preLoaderRoute: typeof CSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$doctorId': {
      id: '/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ClinicRouteChildren {
  ClinicOnboardingRoute: typeof ClinicOnboardingRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
}

const ClinicRouteChildren: ClinicRouteChildren = {
  ClinicOnboardingRoute: ClinicOnboardingRoute,
  ClinicIndexRoute: ClinicIndexRoute,
}

const ClinicRouteWithChildren =
  ClinicRoute._addFileChildren(ClinicRouteChildren)

interface PatientRouteChildren {
  PatientAppointmentsRoute: typeof PatientAppointmentsRoute
  PatientFavoritesRoute: typeof PatientFavoritesRoute
  PatientProfileRoute: typeof PatientProfileRoute
  PatientIndexRoute: typeof PatientIndexRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientAppointmentsRoute: PatientAppointmentsRoute,
  PatientFavoritesRoute: PatientFavoritesRoute,
  PatientProfileRoute: PatientProfileRoute,
  PatientIndexRoute: PatientIndexRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ClinicRoute: ClinicRouteWithChildren,
  ClinicsRoute: ClinicsRoute,
  ContactRoute: ContactRoute,
  ForClinicsRoute: ForClinicsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PatientRoute: PatientRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  CSlugRoute: CSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
